### PR TITLE
Adding artman_iam.yaml, plus dependencies declarations

### PR DESCRIPTION
**Pull request by garrettjonesgoogle**

### CODE REVIEW

**Comment by michaelbausor** [comment]
LGTM

**Comment by jmuk** [comment]
LGTM too

**Comment by garrettjonesgoogle** [comment]
I made a rename because I think 'dependencies' was too general - PTAL

**Comment by michaelbausor** [comment]
LGTM

**Comment by garrettjonesgoogle** [comment]
As mentioned in the artman PR, another update had to be made - a new config line 'desc_proto_path' has been added. 

Also, the gcloud-java repo has been renamed to google-cloud-java, so I updated those lines too.

**Pull request merged**
