### PR TITLE
Add LRO config to functions_gapic.yaml

### PR DESCRIPTION
**Pull request by jmuk**

### CODE REVIEW

**Comment by jmuk** [comment]
cc: @jmdobry

**Comment by landrito** [comment]
This LGTM once the `"google/cloud/functions/v1beta2/operations.proto"` is imported in `functions.proto`.

**Comment by jmuk** [comment]
Ah, but we want @stephenplusplus to release a new version of `google-proto-files` to have that line, before regenerating for Node.JS.

**Comment by stephenplusplus** [comment]
Just released google-proto-files@0.8.6. Can you confirm what you need is in there?

**Comment by jmdobry** [comment]
Confirmed, it's there.

**Pull request merged**
