### PR TITLE
Go: Configure Pubsub to use IAM library

### PR DESCRIPTION
**Pull request by pongad**

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
Could you recreate this PR on a freshly synchronized branch (after the scrub that @bjwatson recommends)?

**Comment by bjwatson** [comment]
I think @pongad can apply my scrubbing instructions to this branch.

**Comment by pongad** [comment]
I believe that does it. Could @bjwatson please verify?

**Comment by bjwatson** [comment]
@pongad Scrubbing looks good to me.

**Comment by pongad** [comment]
@bjwatson Thank you, @garrettjonesgoogle PTAL

**Comment by garrettjonesgoogle** [comment]
LGTM

**Pull request merged**
