### PR TITLE
Add GAPIC configuration files

### PR DESCRIPTION
**Pull request by geigerj**

### CODE REVIEW

**Comment by geigerj** [comment]
FYI: @ethanbao @garrettjonesgoogle

**Comment by tbetbetbe** [comment]
LGTM 👍 

FYI: @jmuk, in case you are looking into adding a ruby pipeline

Please wait for LGTM from @garrettjonesgoogle and @ethanbao

**Comment by garrettjonesgoogle** [comment]
LGTM

**Comment by jmuk** [comment]
Great!
I've actually added the Ruby config into the internal repo already, you can pull it (or I can do it later)

**Pull request merged**
