### PR TITLE
Add boilerplate needed for namespace package on Python 2.x.

### PR DESCRIPTION
**Pull request by tseaver**
See https://groups.google.com/forum/#!topic/googleapis/KFYgApEo7FQ.

### CODE REVIEW

**Comment by tbetbetbe** [comment]
FYI: 

- There's is now a WIP tool for building packages from the service definitions in this repo.
- Please see [packman](https://www.npmjs.com/package/googleapis-packman), whose source is at https://github.com/googleapis/packman. 
- It needs protoc and the grpc language plugins to be installed as a prerequisite, but once present it runs protoc and builds packages 
- It's built the following
  * [python common protos](https://pypi.python.org/pypi/googleapis-common-protos)
  * [ruby common protos](https://rubygems.org/gems/googleapis-common-protos)
  * [the python grpc pubsub package](https://pypi.python.org/pypi/grpc-google-pubsub-v1)

with more to come.

**Comment by wora** [comment]
@craigcitro Shall we still add this?

**Comment by bjwatson** [comment]
@tseaver Can this be closed?

**Comment by tseaver** [comment]
I just verified that generated packages do have the `google/__init__.py` in their sdists.  I think this is safe to close.

**Pull request closed without merging**
