### PR TITLE
Update GAPIC configs

### PR DESCRIPTION
**Pull request by geigerj**
Corresponds to the toolkit refactoring, googleapis/toolkit#71

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
LGTM

**Comment by bjwatson** [comment]
LGTM2

It occurs to me that we might move language_provider up a level again, because it no longer varies between templates. Just a thought for a future PR.

**Comment by geigerj** [comment]
Agreed -- let's file that as an issue in the toolkit repo.

**Comment by bjwatson** [comment]
@geigerj Okay, let's see how it plays out with language_provider being at the template level.

**Pull request merged**
