### PR TITLE
feat: add new PHP surface for compute v1

### PR DESCRIPTION
**Pull request by bshaffer**
Sets `migration_mode = "MIGRATION_MODE_UNSPECIFIED"` for the compute gapic clients.

This means that the new (v2) client surfaces will be generated, but everything else (e.g. samples) will stay on the V1 surface. This is the default for ALL client surfaces which are GA

### CODE REVIEW

**Comment by bshaffer** [comment]
The kokoro job is failing with the following error and I'm not sure why... is it possible that the `WORKSPACE` needs to be updated for compute differently than in google3?

```
ERROR: /tmpfs/src/github/googleapis/google/cloud/compute/v1/BUILD.bazel:278:18: @//google/cloud/compute/v1:compute_php_gapic_srcjar: `bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc --experimental_allow_proto3_optional --plugin=protoc-gen-gapic=bazel-out/k8-opt-exec-2B5CBBC6/bin/external/gapic_generator_php/rules_php_gapic/php_gapic_generator_binary_run.sh --gapic_out=metadata,transport=rest,migration-mode=MIGRATION_MODE_UNSPECIFIED,generate-snippets,service_yaml=google/cloud/compute/v1/compute_v1.yaml,grpc_service_config=google/cloud/compute/v1/compute_grpc_service_config.json:bazel-out/k8-fastbuild/bin/google/cloud/compute/v1/compute_php_gapic_srcjar.srcjar.zip -Igoogle/cloud/compute/v1/compute.proto=google/cloud/compute/v1/compute.proto -Igoogle/api/annotations.proto=google/api/annotations.proto -Igoogle/api/http.proto=google/api/http.proto -Igoogle/protobuf/descriptor.proto=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src/google/protobuf/_virtual_imports/descriptor_proto/google/protobuf/descriptor.proto -Igoogle/api/client.proto=google/api/client.proto -Igoogle/api/launch_stage.proto=google/api/launch_stage.proto -Igoogle/protobuf/duration.proto=bazel-out/k8-fastbuild/bin/external/com_google_protobuf/src/google/protobuf/_virtual_imports/duration_proto/google/protobuf/duration.proto -Igoogle/api/field_behavior.proto=google/api/field_behavior.proto -Igoogle/api/resource.proto=google/api/resource.proto -Igoogle/cloud/extended_operations.proto=google/cloud/extended_operations.proto -Igoogle/cloud/common_resources.proto=google/cloud/common_resources.proto google/cloud/compute/v1/compute.proto google/cloud/common_resources.proto` failed: (Exit 1): protoc failed: error executing command (from target //google/cloud/compute/v1:compute_php_gapic_srcjar) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc --experimental_allow_proto3_optional ... (remaining 15 arguments skipped)
```

**Comment by bshaffer** [comment]
After painful debugging, this error goes away if I remove a certain number of services from `compute.proto`. As long as the number is 64 services, the build succeeds. It also works if I use `NEW_SURFACE_ONLY` as the `migration_mode`, as this would result in half the generated services.

I think this is because of a OOM error or some other out-of-resource error.

**Comment by bshaffer** [comment]
Is it possible this could be because of the `memory_limit=512M` set for the php command in [rules_php_gapic/php.bzl](https://github.com/googleapis/gapic-generator-php/blob/main/rules_php_gapic/php.bzl#L65)?

cc @noahdietz

**Comment by noahdietz** [comment]
> Is it possible this could be because of the `memory_limit=512M` set for the php command in [rules_php_gapic/php.bzl](https://github.com/googleapis/gapic-generator-php/blob/main/rules_php_gapic/php.bzl#L65)?
> 
> See [googleapis/gapic-generator-php#631](https://github.com/googleapis/gapic-generator-php/pull/631)

Possibly! didn't realize there was a limit imposed

**Comment by bshaffer** [comment]
@vchudnov-g @vam-google these tests are now passing but I'm not sure what the approval process is. Can one of you merge this?

**Pull request merged**
