### PR TITLE
Add semver config files

### PR DESCRIPTION
**Pull request by tbetbetbe**
- Adds configuration for the semantic version to use in packages being generated from the services.

### CODE REVIEW

**Comment by wora** [comment]
I am not sure why this is needed. The major api version is declared in the proto package name. The patch indicates server bug fixes, which don't require client changes. The question is where do we get the minor version from. I think we need to find a way for API owners to declare such version. We, as repo maintainers, should not assign the versions.

**Comment by tbetbetbe** [comment]
- the major version of any semver-released package needs to be able to vary independently of the api version.
  - e.g today google-apis-pubsub-python is released at 1.0.0 with along grpc-python.0.9.0a3
  - grpc-python updates with an api change grpc-python-1.1 which contains a breaking api change
  - google-apis-pubsub-python needs to be re-released
     - it cannot use semver 1.x.x even though the proto api has not changed, it must now be 2.0.0

**Comment by wora** [comment]
For each API, we should generate api package with name like grpc-google-pubsub-v1, and the dependencies contribute to the package version, such as 0.9.0. But the package version should be consistent across all APIs. It should be configured centrally, not per API. Right?

**Comment by bjwatson** [comment]
@tbetbetbe Can this be closed?

**Comment by guptasu** [comment]
Seems like this is now out of date. As per request from @wora , let's close this PR for the sake of cleanup and we can create another one when we need to add symver information.

**Pull request closed without merging**
