### PR TITLE
Introduce language v1 proto and yaml file

### PR DESCRIPTION
**Pull request by jmuk**

### CODE REVIEW

**Comment by jmuk** [comment]
cc: @bjwatson @anthmgoogle 
Note that this PR will not be merged until it's ready.

**Comment by bjwatson** [comment]
@jmuk LGTM, once it's time to merge this.

**Comment by bjwatson** [comment]
FYI @swcloud, @jskeet, @jba, and @michaelbausor. These are the protos and config files you will need.

**Comment by jba** [comment]
@pongad

**Comment by pongad** [comment]
@jba Thank you for pinging me. I'll update genproto and cloud.google.com/go and keep you posted.

**Comment by bjwatson** [comment]
@jmuk You have my LGTM from last week.

**Comment by jmuk** [comment]
The new proto file has been merged through the automated tool. Now this PR is only for yaml files.

**Comment by jmuk** [comment]
Note to language owners: if you already generated the GAPIC files last week with this PR, you don't have to regenerate them. The proto pushed to master is slightly different on some comments, but it won't affect GAPIC.

**Comment by bjwatson** [comment]
Thanks @jmuk!

**Comment by swcloud** [comment]
@jmuk Good to know!

**Pull request merged**
