### PR TITLE
Index the packages we have and plan to deliver to gcloud-python

### PR DESCRIPTION
**Pull request by bjwatson**
Updates https://github.com/GoogleCloudPlatform/gcloud-python/issues/1384

### CODE REVIEW

**Comment by bjwatson** [comment]
FYI @tseaver and @dhermes

**Comment by dhermes** [comment]
:+1: Thanks!

**Comment by geigerj** [comment]
LGTM

**Comment by tseaver** [comment]
@bjwatson Oops, I don't see the `grpc-google-longrunning-v#` or `gax-google-longrunning-v#` releases on that list.

**Comment by bjwatson** [comment]
Thanks @tseaver. Good catch. I've added `longrunning`.

**Comment by tseaver** [comment]
@bjwatson that change LGTM

**Pull request merged**
