### PR TITLE
Add Java staging paths

### PR DESCRIPTION
**Pull request by shinfan**

### CODE REVIEW

**Comment by shinfan** [comment]
Friendly ping

**Comment by michaelbausor** [comment]
LGTM - it would also be nice to do some of the other APIs, even if it is not necessary yet (such as cloud debugger, datastore, bigtable, functions)

**Comment by shinfan** [comment]
@michaelbausor I feel it is confusing to setup staging paths for APIs that do not exist in the java staging repo. We can add the paths on demand if we need in the future.

**Comment by michaelbausor** [comment]
Unfortunately they already have paths, just the wrong ones after the change: https://github.com/googleapis/googleapis/blob/master/gapic/api/artman_datastore.yaml#L41

**Comment by shinfan** [comment]
Oh that's a different story then. I will update these paths as well.

**Pull request closed without merging**
