### PR TITLE
Renaming longrunning output packages

### PR DESCRIPTION
**Pull request by garrettjonesgoogle**

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
Switching to gax repos instead (per internal thread).

**Comment by garrettjonesgoogle** [comment]
Another update - removing 'cloud' from the package names.

**Comment by garrettjonesgoogle** [comment]
PS I'm looking for a new "LGTM" because the original changes are all overwritten now.

**Comment by bjwatson** [comment]
I'm okay with what I see, but let's wait until Monday for feedback from anyone else. For example, @jmuk is busy with other things today.

**Comment by jmuk** [comment]
So the decision is longrunning.Operations as a part of gax of each languages?

I'm good with this config, but please note that it would require manual edits for NodeJS (I can do that on my side).

**Comment by garrettjonesgoogle** [comment]
Well, I consider this PR to be the ratification of the proposal :-)

**Comment by geigerj** [comment]
+1, but please let @bjwatson give final approval.

**Comment by bjwatson** [comment]
@garrettjonesgoogle LGTM

**Pull request merged**
