### PR TITLE
Added support for the Check error code API_TARGET_BLOCKED

### PR DESCRIPTION
**Pull request by mangchiandjjoe**

### CODE REVIEW

**Comment by mangchiandjjoe** [comment]
This PR was not merged yet. 

@saknarin444 Is there any ETA on this?

**Comment by 0946752671** [comment]
Like 👍

**Comment by gunsch** [comment]
The original change has been submitted internally and synced to this repo via https://github.com/googleapis/googleapis/commit/b509315fbb5c26f0021007ffb655b64a17ecea5a

Feel free to close this issue.

**Comment by qiwzhang** [comment]
@mangchiandjjoe  This PR can be closed.  The error code is ready in.

**Comment by shellscape** [comment]
Folks. I just ran into `"Request blocked due to unsupported error code: 122"` coming back from ESP. There's _absolutely no mention of this anywhere in the documentation_. The only meaningful reference to this coming back from Google is this Google Groups post from May of _last year_ : https://groups.google.com/forum/#!topic/google-cloud-endpoints/Iksax1bWHLA

It's incredibly irresponsible to let documentation get this far out of date. Hopefully someone from the team that can affect some change sees this.

**Comment by shellscape** [comment]
_(apologies for the successive replies, I wanted to make sure this got noticed via notifications)_

@gunsch the documentation does not reflect nor mention the change in b509315. please see my previous reply. this is a significant hole in the docs

**Comment by gunsch** [comment]
@shellscape I'm no longer on the project, but I suspect you want https://github.com/cloudendpoints/esp/issues/573 . This repo is not responsible for nor dependent on ESP.

**Comment by qiwzhang** [comment]
@shellscape It is an ESP bug.  https://github.com/cloudendpoints/esp/pull/581 will fix it.  The changes will be in next ESP release (in a couple weeks).

**Comment by qiwzhang** [comment]
@mangchiandjjoe could you close this PR?  It is not needed.

**Pull request closed without merging**
