### PR TITLE
Script to correct timeouts in generated GAPIC configs

### PR DESCRIPTION
**Pull request by jcanizales**
I'm using this as part of a script that runs the whole pipeline to generate a GAPIC config. It's called after the output file is extracted from the downloaded .tar.gz.

I'm not sure where to put the overall script, but as this is an independent piece of it I guess other people can use it meanwhile.

### CODE REVIEW

**Comment by geigerj** [comment]
Please fix this in the GAPIC config generator rather than using a script: https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/config/RetryGenerator.java#L71

**Comment by garrettjonesgoogle** [comment]
This script shouldn't exist at all; if the default value is wrong, correct it in https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/config/RetryGenerator.java .

**Comment by jcanizales** [comment]
Hm, the change to 20s was done on purpose here: https://github.com/googleapis/toolkit/commit/9652cb012458e299e2077ad67e5472cba0dca2b3#diff-9e97bbb6fd5002f21f2a66633fa62d93

So which should it be?

**Comment by garrettjonesgoogle** [comment]
I've never been sure :-) Why did you want it to be set to 60 s?

**Comment by jcanizales** [comment]
@bjwatson's doing it by hand. Brian, why not 20?

**Comment by bjwatson** [comment]
I don't really know either? I thought we've been using all 60s across the board for other APIs.

Agreed that this should not be scripted. We should update the default instead.

**Comment by jcanizales** [comment]
Hehe so if we don't have reasons to prefer one over the other, can we just leave it this way? 20s sounds as reasonable to me as 60s.

**Comment by bjwatson** [comment]
@garrettjonesgoogle Who made the decision on 20 vs. 60s to begin with? They should be looped into this discussion.

**Comment by garrettjonesgoogle** [comment]
@bjwatson I made the decision, somewhat arbitrarily.

**Comment by bjwatson** [comment]
@garrettjonesgoogle Ok, then let's stop changing the timeout unless we find a reason to keep doing so.

**Comment by bjwatson** [comment]
@jcanizales Looks like this PR can be closed. Can someone add an agenda item to discuss this next week, or start an email thread to discuss with the team? We should make a decision and apply it across the board to all APIs (except for any that need a custom timeout).

**Comment by jcanizales** [comment]
I'll start a thread.

**Comment by bjwatson** [comment]
Thanks @jcanizales

**Pull request closed without merging**
