### PR TITLE
Rename Logging to StackDriver in summary

### PR DESCRIPTION
**Pull request by pongad**

### CODE REVIEW

**Comment by pongad** [comment]
cc https://github.com/GoogleCloudPlatform/google-cloud-go/pull/352

**Comment by garrettjonesgoogle** [comment]
Could you recreate this PR on a freshly synchronized branch (after the scrub that @bjwatson recommends)?

**Comment by bjwatson** [comment]
I think @pongad can apply my scrubbing instructions to this branch.

**Comment by pongad** [comment]
I believe that does it. Could @bjwatson please verify?

**Comment by bjwatson** [comment]
@pongad Scrubbing looks good to me.

BTW, why not update the comment at the top of the file, too?

**Comment by pongad** [comment]
Good catch, PTAL @garrettjonesgoogle

**Comment by garrettjonesgoogle** [comment]
LGTM

**Pull request merged**
