### PR TITLE
Add package_deps.yml

### PR DESCRIPTION
**Pull request by tbetbetbe**
Configures the semantic versions of the dependencies to use when generating 
googleapis packages from the api protos

### CODE REVIEW

**Comment by wora** [comment]
I think this file should be auto generated by the release process and be part of the output in another repo. The source repo should not need to have these information. The general concept is people can use this repo to generate any client/server/docset as they need, we don't need to dictate any dependency.

**Comment by tbetbetbe** [comment]
> and be part of the output in another repo

Which one?  At the moment, this is the only repo needed when generating gRPC-based packages.
We could put the generated file in another repo, but then the tool that builds the packages needs to get its info from two sources.

IMHO, its simpler for tools (and humans) if it lives here.
- tools doing any processing get all their info from one source and there is minimal chance of inconsistencies occurring
- Non-grpc tools that don't need the dependency info can just ignore its contents.

**Comment by wora** [comment]
This looks good. Do you want to update the version numbers before I merge it?

**Comment by tbetbetbe** [comment]
Sorry, about the lag in the response - I will update the version numbers in a commit later today.

**Comment by garrettjonesgoogle** [comment]
It seems that this has gotten somewhat out of date in comparison to https://github.com/googleapis/packman/blob/master/config/dependencies.yml .

At a higher level, the toolkit team as agreed that it would be a good idea to move the versions from packman into googleapis. This will require a coordinated change across multiple repositories (packman/artman/googleapis). Maybe the present PR should be closed and a new effort should be taken up for moving the version config.

**Comment by guptasu** [comment]
As per request from @wora , seems like this is now out of date. Let's close this PR for the sake of cleanup and we can create another one when we need to add symver information.

**Pull request closed without merging**
