### PR TITLE
Language v1beta2 configs.

### PR DESCRIPTION
**Pull request by landrito**

### CODE REVIEW

**Comment by landrito** [comment]
Since both v1 and v1beta2 are going to be used, I followed the pattern set in https://github.com/googleapis/googleapis/pull/299 to have the artman yamls and service yamls of each version present.

**Comment by landrito** [comment]
Ping.

**Comment by jskeet** [comment]
I don't know enough about the gapic syntax to verify that it looks good, to be honest. Will take a little tweak to my scripts to get it to generate for C# I suspect, but that's fine. Will try to generate in the morning.

**Comment by landrito** [comment]
Thanks for the review @geigerj!

Thanks @jskeet for looking!

I'm going to go ahead and merge so that other languages are not blocked by this. 

If after you try tomorrow morning, you find some needed changes, lets handle that in a subsequent PR.

**Pull request merged**
